spring:
  datasource:
    url: ${db.url}
    username: ${db.user}
    password: ${db.password}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    default-schema: public
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
    open-in-view: false

server:
  port: 8079
